import psycopg2

def check_columns():
    try:
        conn = psycopg2.connect(host="127.0.0.1", database="reboot_db", user="slyeee", password="")
        cur = conn.cursor()
        
        # Check users_user columns
        print("Checking 'users_user' columns...")
        cur.execute("SELECT column_name FROM information_schema.columns WHERE table_name = 'users_user';")
        cols = [r[0] for r in cur.fetchall()]
        print(f"Columns: {cols}")
        
        needed = ['risk_level', 'center_id']
        missing = [c for c in needed if c not in cols]
        
        if missing:
            print(f"MISSING Columns in users_user: {missing}")
            # Fix it?
            for m in missing:
                if m == 'risk_level':
                    print("Adding 'risk_level'...")
                    cur.execute("ALTER TABLE users_user ADD COLUMN risk_level varchar(10) DEFAULT 'LOW';")
                elif m == 'center_id':
                    print("Adding 'center_id'...")
                    cur.execute("ALTER TABLE users_user ADD COLUMN center_id integer;")
            conn.commit()
            print("Fixed users_user columns.")
        else:
            print("users_user has all needed columns.")
            
        # Check centers_center
        print("Checking 'centers_center' table...")
        cur.execute("SELECT count(*) FROM information_schema.tables WHERE table_name = 'centers_center';")
        exists = cur.fetchone()[0]
        if not exists:
            print("'centers_center' table MISSING. Creating it...")
            # Create simple Center table
            SQL_CENTER = """
            CREATE TABLE centers_center (
                id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                name varchar(100) NOT NULL,
                code varchar(50) NOT NULL UNIQUE,
                created_at timestamp with time zone NOT NULL DEFAULT now()
            );
            """
            cur.execute(SQL_CENTER)
            conn.commit()
            print("Created 'centers_center'.")
        else:
            print("'centers_center' exists.")

        conn.close()
    except Exception as e:
        print(f"Error: {e}")

if __name__ == "__main__":
    check_columns()
