import psycopg2

def force_create_diaries():
    SQL_CREATE = """
    CREATE TABLE IF NOT EXISTS "diaries" (
        "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        "event" text NULL,
        "mood_intensity" integer NOT NULL,
        "emotion_desc" text NULL,
        "emotion_meaning" text NULL,
        "self_talk" text NULL,
        "ai_comment" text NULL,
        "ai_emotion" text NULL,
        "safety_flag" boolean NOT NULL,
        "created_at" timestamp with time zone NOT NULL,
        "user_id" bigint NOT NULL
    );
    """
    
    SQL_CONSTRAINT = """
    ALTER TABLE "diaries" 
    ADD CONSTRAINT "fk_diaries_users_user" 
    FOREIGN KEY ("user_id") 
    REFERENCES "users_user" ("id") 
    DEFERRABLE INITIALLY DEFERRED;
    """
    
    SQL_INDEX = """
    CREATE INDEX IF NOT EXISTS "diaries_user_id_idx" ON "diaries" ("user_id");
    """
    
    conn = None
    try:
        conn = psycopg2.connect(host="127.0.0.1", database="reboot_db", user="slyeee", password="")
        cur = conn.cursor()
        
        print("Creating Table 'diaries'...")
        cur.execute(SQL_CREATE)
        
        print("Checking Constraint...")
        # Simplistic check if constraint exists or just catch error
        try:
            cur.execute(SQL_CONSTRAINT)
            print("Constraint Added.")
        except Exception as e:
            print(f"Constraint might exist: {e}")
            conn.rollback()
            
        print("Creating Index...")
        cur.execute(SQL_INDEX)
        
        conn.commit()
        print("SUCCESS: Diaries Table Ready.")
        
    except Exception as e:
        print(f"Error Creating Table: {e}")
        if conn: conn.rollback()
    finally:
        if conn: conn.close()
        
if __name__ == "__main__":
    force_create_diaries()
