DO
$do$
BEGIN
   IF NOT EXISTS (
      SELECT FROM pg_catalog.pg_roles
      WHERE  rolname = 'maumON_admin') THEN

      CREATE ROLE "maumON_admin" LOGIN PASSWORD 'maumON_1234';
   END IF;
END
$do$;

ALTER ROLE "maumON_admin" WITH SUPERUSER CREATEDB CREATEROLE REPLICATION BYPASSRLS;
ALTER DATABASE reboot_db OWNER TO "maumON_admin";
GRANT ALL PRIVILEGES ON DATABASE reboot_db TO "maumON_admin";
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO "maumON_admin";
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO "maumON_admin";
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO "maumON_admin";
