# Generated by Django 5.2.10 on 2026-01-27 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaumOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="일기 내용")),
                ("mood_score", models.IntegerField(verbose_name="감정 점수 (1-10)")),
                (
                    "analysis_result",
                    models.JSONField(
                        blank=True, null=True, verbose_name="AI 분석 결과"
                    ),
                ),
                (
                    "is_high_risk",
                    models.BooleanField(default=False, verbose_name="위험 징후"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "마음온 (감정 일기)",
                "verbose_name_plural": "마음온 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
