# Generated by Django 4.2.27 on 2026-01-28 05:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("haru_on", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="maumon",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="작성일"
            ),
        ),
    ]
