# Generated by Django 5.2.10 on 2026-02-15 11:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("haru_on", "0002_alter_maumon_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HaruOn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        db_column="event", null=True, verbose_name="일기 내용"
                    ),
                ),
                (
                    "mood_score",
                    models.IntegerField(
                        db_column="mood_intensity",
                        default=3,
                        verbose_name="감정 점수 (1-10)",
                    ),
                ),
                ("emotion_desc", models.TextField(null=True)),
                ("emotion_meaning", models.TextField(null=True)),
                ("self_talk", models.TextField(null=True)),
                ("ai_comment", models.TextField(null=True)),
                ("ai_emotion", models.TextField(null=True)),
                (
                    "is_high_risk",
                    models.BooleanField(
                        db_column="safety_flag", default=False, verbose_name="위험 징후"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="작성일"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        db_column="user_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="diaries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "하루온 (감정 일기)",
                "verbose_name_plural": "하루온 목록",
                "db_table": "diaries",
                "ordering": ["-created_at"],
                "managed": True,
            },
        ),
        migrations.DeleteModel(
            name="MaumOn",
        ),
    ]
