# Generated by Django 5.2.10 on 2026-01-27 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="센터명")),
                ("region", models.CharField(max_length=50, verbose_name="관할 지역")),
                (
                    "admin_email",
                    models.EmailField(max_length=254, verbose_name="담당자 이메일"),
                ),
            ],
            options={
                "verbose_name": "보건소/센터",
                "verbose_name_plural": "보건소/센터 목록",
            },
        ),
        migrations.CreateModel(
            name="VerificationCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=12, unique=True, verbose_name="인증 코드"
                    ),
                ),
                (
                    "is_used",
                    models.BooleanField(default=False, verbose_name="사용 여부"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification_codes",
                        to="centers.center",
                    ),
                ),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="used_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "일회용 인증 코드",
                "verbose_name_plural": "일회용 인증 코드 목록",
            },
        ),
    ]
