# Generated by Django 5.2.10 on 2026-01-27 10:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("centers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="B2GConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "승인 대기"),
                            ("ACTIVE", "연동 중"),
                            ("REVOKED", "해지됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="정보 제공 동의 일시"
                    ),
                ),
                (
                    "expired_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="만료 일시"
                    ),
                ),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to="centers.center",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "기관 연동 정보",
                "verbose_name_plural": "기관 연동 목록",
            },
        ),
    ]
