name: MindDiaryApp
options:
  bundleIdPrefix: com.slyeee
  deploymentTarget:
    iOS: "17.0"
targets:
  MindDiaryApp:
    type: application
    platform: iOS
    sources:
      - path: APIService.swift
      - path: DataSeeder.swift
      - path: .
        excludes:
          - Package.swift
          - Package.resolved
          - project.yml
          - create_appicon.py
          - create_assets.py
          - make_icons.py
          - .build
          - .github
          - .agent
    info:
      path: Info.plist
      properties:
        CFBundleDisplayName: "Maum-on"
        CFBundleName: "Maum-on"
        UILaunchStoryboardName: "LaunchScreen"
    dependencies:
      - package: mlx-swift
        product: MLX
      - package: mlx-swift
        product: MLXRandom
      - package: mlx-swift-lm
        product: MLXLMCommon
      - package: mlx-swift-lm
        product: MLXLLM
      - sdk: Metal.framework
      - sdk: MetalKit.framework
      - sdk: MetalPerformanceShaders.framework
      - sdk: Accelerate.framework
      - sdk: Foundation.framework
      - sdk: UIKit.framework
      - sdk: SwiftUI.framework
      - sdk: CoreGraphics.framework
      - sdk: CoreAudio.framework
      - sdk: AVFoundation.framework
    settings:
      Check Pods Manifest.lock: false
      INFOPLIST_FILE: Info.plist
      PRODUCT_BUNDLE_IDENTIFIER: com.slyeee.MindDiaryApp
      ENABLE_BITCODE: NO
      LD_RUNPATH_SEARCH_PATHS: ["$(inherited)", "@executable_path/Frameworks"]
      OTHER_LDFLAGS:
        [
          "$(inherited)",
          "-framework",
          "Metal",
          "-framework",
          "MetalPerformanceShaders",
          "-framework",
          "Accelerate",
          "-framework",
          "Foundation",
          "-lc++",
          "-ObjC",
        ]
      SWIFT_VERSION: 5.0
      TARGETED_DEVICE_FAMILY: "1"
      CLANG_CXX_LANGUAGE_STANDARD: "gnu++17"
      CLANG_CXX_LIBRARY: "libc++"
      ENABLE_USER_SCRIPT_SANDBOXING: NO
packages:
  mlx-swift:
    url: https://github.com/ml-explore/mlx-swift.git
    from: 0.10.0
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm.git
    branch: main
